/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasFinal;

import Controlador.ControladorCategoria;
import Controlador.ControladorProducto;
import Controlador.ControladorProveedor;
import VistasFinal.Login;
import Controlador.ControladorUsuario;
import Modelo.bCategoria;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.IntelliJTheme;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.EventQueue;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author FABIAN CAMPOVERDE
 */
public class UpdateProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    
   private static List<bCategoria> cate;
   static List<String> lista= new ArrayList<>();
    public UpdateProducto() {
        initComponents();
        
         cate=ControladorCategoria.listar(1);
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        for (int i = 0; i < cate.size(); i++) {
            comboBoxModel.addElement(cate.get(i).getNombre());
            
        }
//        comboBoxModel = (DefaultComboBoxModel) categoria.getModel();
        categoria.setModel(comboBoxModel);
        if (!lista.isEmpty()) {
            codigo.setText(lista.get(1));
            nombre.setText(lista.get(2));
            medida.setSelectedItem(lista.get(3));           
            categoria.setSelectedItem(lista.get(4));
            stock.setValue(Integer.parseInt(lista.get(5)));
            minimo.setValue(Integer.parseInt(lista.get(6)));
        }
        codigo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        medida = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        stock = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        minimo = new javax.swing.JSpinner();
        update = new javax.swing.JButton();
        modo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "",
            new String[]{
                "font:bold +10",
                "font:bold +1",
                "",
                "showClearButton:true;JTextField.placeholderText=Escolar",
                "",
                "showClearButton:true;JTextField.placeholderText=Para campaña escolar",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail",
                "al trail",
                ""
            }
        ));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS ");
        crazyPanel1.add(jLabel1);

        jLabel3.setText("*Campo obligatorio");
        crazyPanel1.add(jLabel3);

        jLabel4.setText("Codigo");
        crazyPanel1.add(jLabel4);
        crazyPanel1.add(codigo);

        jLabel2.setText("Nombre");
        crazyPanel1.add(jLabel2);
        crazyPanel1.add(nombre);

        jLabel5.setText("Medida");
        crazyPanel1.add(jLabel5);

        medida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unidades", "Kilogramos", "Gramos", "Bolsa", "Caja", "Litros", "Mililitros", " " }));
        crazyPanel1.add(medida);

        jLabel8.setText("Stock");
        crazyPanel1.add(jLabel8);
        crazyPanel1.add(stock);

        jLabel9.setText("Categoria");
        crazyPanel1.add(jLabel9);

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        crazyPanel1.add(categoria);

        jLabel6.setText("Stock Minimo");
        crazyPanel1.add(jLabel6);
        crazyPanel1.add(minimo);

        update.setText("ACTUALIZAR");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        crazyPanel1.add(update);

        modo.setText("Modo");
        modo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modoMouseClicked(evt);
            }
        });
        modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGISTRO DE PRODUCTOS");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 479, Short.MAX_VALUE)
                        .addComponent(modo)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modo)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crazyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void Datos(List<String> datos){
        lista=datos;
}
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
//     
//                int newY = (this.getHeight() - user.getHeight()) / 2; // Mantenemos la posición vertical
//                user.setLocation(user.getX(), newY);
//
//                // Ajustamos la posición horizontal en función del ancho de la ventana
//                int xOffset = this.getWidth() / 4; // Cambia este valor según tus preferencias
//                user.setLocation(275,45);

    }//GEN-LAST:event_formComponentResized

    private void modoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoActionPerformed
        if (!FlatLaf.isLafDark()) {
            EventQueue.invokeLater(() -> {
                modo.setIcon(new FlatSVGIcon("Img/sun.svg"));
                modo.setText("Dia");
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();

            });

        } else {
            EventQueue.invokeLater(() -> {
                modo.setIcon(new FlatSVGIcon("Img/moon.svg"));
                modo.setText("Noche");
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();

            });
        }

    }//GEN-LAST:event_modoActionPerformed
    private MenuProducto menu;

    public void Update(MenuProducto menuCategoria) {
        this.menu= menuCategoria;
    }
    private void modoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoMouseClicked

    }//GEN-LAST:event_modoMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int cod,cantidad,cantidad_min;
        String name,med,catego;      
        name=nombre.getText();
        med= (String) medida.getSelectedItem();
        cantidad= (int) stock.getValue();
        catego= (String) categoria.getSelectedItem();
        cantidad_min= (int) minimo.getValue();
        
        if (codigo.getText().equals("") || name.equals("") || med.equals("") || cantidad==0 || catego.equals("") || cantidad_min==0) {
            JOptionPane.showMessageDialog(null, "Ingresar no vacios");
        }
        else{        
            cod=Integer.parseInt(codigo.getText());
            if(cantidad>0 && cantidad_min>0){
            ControladorProducto.setDatosProducto(cod, name, med, cantidad, catego, null, cantidad_min);
            String msg=ControladorProducto.decisor(2);
            if (msg.equals("Codigo ya existente")) {
                JOptionPane.showMessageDialog(null, msg);
            } else {
                JOptionPane.showMessageDialog(null, msg);
                nombre.setText("");
                codigo.setText("");
                medida.setSelectedItem("Unidades");
                stock.setValue(0);
                categoria.setSelectedItem(cate.get(0).getNombre());
                minimo.setValue(0);
                menu.actualizarTabla();
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "Ingresar datos positivos");
            } 
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLaf.registerCustomDefaultsSource("Prop");
        FlatLightLaf.setup();
        //IntelliJTheme.setup(RegistroUsuario.class.getResourceAsStream("/template.theme.json"));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProducto().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField codigo;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox medida;
    private javax.swing.JSpinner minimo;
    private javax.swing.JButton modo;
    private javax.swing.JTextField nombre;
    private javax.swing.JSpinner stock;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
